<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.treblereel.gwt.nio</groupId>
        <artifactId>gwt-nio-parent</artifactId>
        <version>1.6</version>
    </parent>

    <artifactId>gwt-nio-emul</artifactId>
    <packaging>jar</packaging>

    <name>GWT/J2CL compatible NIO emulation</name>
    <description>GWT/J2CL compatible NIO emulation</description>

    <dependencies>
        <dependency>
            <groupId>org.treblereel.gwt.nio</groupId>
            <artifactId>gwt-nio-support</artifactId>
            <version>${project.version}</version>
        </dependency>
    </dependencies>

    <build>
        <resources>
            <resource>
                <directory>src/main/java</directory>
                <includes>
                    <include>**/*.java</include>
                    <include>**/*.js</include>
                </includes>
            </resource>
            <resource>
                <directory>src/main/resources</directory>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <artifactId>maven-compiler-plugin</artifactId>
                <groupId>org.apache.maven.plugins</groupId>
                <version>${maven.compiler.plugin}</version>
                <configuration>
                    <excludes>
                        <exclude>**/*.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>